### PR TITLE
Added open sans

### PR DESCRIPTION
**Pull request by abhishekgl650**

### CODE REVIEW

**Comment by ishanbagchi** [comment]
@abhishekgl650, can you please tell me your institution and year?

**Comment by abhishekgl650** [comment]
Chandigarh University 3 year @ishanbagchi

**Comment by abhishekgl650** [comment]
hey, @ishanbagchi  please merge my first PR!!

**Comment by ishanbagchi** [comment]
@abhishekgl650, the contributions will be accounted for Hack It competition which is restricted to SIT, Siliguri. The competition will end today, I'll merge your PR after the announcement of results.

**Comment by abhishekgl650** [comment]
Ok @ishanbagchi

**Pull request merged**
